# Generated by Django 4.0.4 on 2022-05-02 10:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_types', models.CharField(max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers_name', models.CharField(max_length=15)),
                ('suppliers_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('suppliers_goods', models.CharField(max_length=15)),
                ('gst_number', models.CharField(max_length=15)),
                ('business_number', models.CharField(max_length=15)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products_Name', models.CharField(max_length=50)),
                ('Products_quantity', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(auto_now_add=True)),
                ('Products_base_price', models.BigIntegerField()),
                ('Products_selling_price', models.BigIntegerField()),
                ('ProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.producttype')),
                ('suppliers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.suppliers')),
            ],
        ),
    ]
