# Generated by Django 4.0.4 on 2022-05-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_details',
            name='suppliers_id',
        ),
    ]
